import { useMemo, type ReactElement } from 'react';
import type { IFundingNode, IReconciliation, ISchemeScenario } from '../domain/fund-flow';
import type { ICitizenStanding } from '../domain/citizen-standing';
import { reconciliationFlagSummary } from '../domain/reconciliation-display';
import { formatCrore } from '../utils/money';

export function buildInformationRequestDraft(
  scenario: ISchemeScenario,
  node: IFundingNode,
  standing: ICitizenStanding,
  reconciliation?: IReconciliation
): string {
  const lines = [
    'Subject: Request for explanation — reported fund standing (synthetic demo draft)',
    '',
    `Scheme: ${scenario.schemeName} (${scenario.schemeCode})`,
    `Period: ${scenario.period}`,
    `Office / place: ${node.name}`,
    `Reported received: ${formatCrore(standing.receivedPaise)}`,
    ''
  ];

  if (reconciliation) {
    lines.push(`Reported status: ${reconciliationFlagSummary(reconciliation)}`);
    for (const item of reconciliation.items) {
      lines.push(`- ${item.label}: ${formatCrore(item.amountPaise)} — ${item.description}`);
    }
    lines.push('');
  } else {
    lines.push(standing.inspectorSummary);
    lines.push('');
  }

  lines.push(
    'I am seeking a plain-language explanation of the reported standing above, including any pending utilisation reports or unpublished onward splits.',
    '',
    'Note: This draft was generated by the ourmoney independent prototype using synthetic demonstration data. It does not allege wrongdoing and is not filed automatically.',
    `Last reported in scenario: ${node.reportedAt}`
  );

  return lines.join('\n');
}

export function InformationRequestPanel({
  draft,
  onClose
}: {
  draft: string;
  onClose: () => void;
}): ReactElement {
  const whatsappUrl = useMemo(() => {
    const text = encodeURIComponent(draft.slice(0, 1800));
    return `https://wa.me/?text=${text}`;
  }, [draft]);

  const copy = async (): Promise<void> => {
    await navigator.clipboard.writeText(draft);
  };

  const share = async (): Promise<void> => {
    if (navigator.share) {
      await navigator.share({ title: 'Information request draft', text: draft });
      return;
    }
    await copy();
  };

  return (
    <div className="info-request-overlay" role="dialog" aria-modal="true" aria-labelledby="info-request-title">
      <div className="info-request-card">
        <header>
          <h2 id="info-request-title">Draft information request</h2>
          <p>Copy-ready text citing this node. Does not file anything automatically.</p>
          <button type="button" className="info-request-close" onClick={onClose} aria-label="Close">×</button>
        </header>
        <textarea readOnly value={draft} rows={14} aria-label="Draft text" />
        <div className="info-request-actions">
          <button type="button" onClick={() => void copy()}>Copy</button>
          <button type="button" onClick={() => void share()}>Share</button>
          <a href={whatsappUrl} target="_blank" rel="noopener noreferrer">WhatsApp</a>
        </div>
      </div>
    </div>
  );
}

export function buildShareText(
  scenario: ISchemeScenario,
  node: IFundingNode,
  standing: ICitizenStanding
): string {
  return [
    `${node.shortName} · ${scenario.schemeName}`,
    `Received ${formatCrore(standing.receivedPaise)}`,
    standing.usedHerePaise > 0 ? `Used here ${formatCrore(standing.usedHerePaise)}` : null,
    standing.ledgerOpenPaise > 0 ? `What's left ${formatCrore(standing.ledgerOpenPaise)}` : null,
    'Synthetic demo · ourmoney.fyi'
  ].filter(Boolean).join(' · ');
}
